#whitelist
branches:
    only:
        - develop

language: cpp

compiler: gcc

before_install:
    - echo "yes" | sudo apt-add-repository ppa:mapnik/boost-backports-1-54
    - echo "yes" | sudo apt-add-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get clean -qq
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    - sudo apt-get install -qq libboost1.54-all-dev

install:
    - export CXX="g++-4.8"
    - export CC="gcc-4.8"

script: mkdir build && cd build && cmake .. && make && make test


